version: '2'

services:

  dash-dwbr:
    image: dash-dwbr
    container_name: dash-dwbr
    restart: unless-stopped
    volumes:
     - ./:/usr/src/app
    ports:
     - "8050:8050"
    environment:
      - TZ=America/Belem

