name: dash-dwbra

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - dash
  - dash-core-components
  - dash-html-components
  - dash-renderer
  - dash-table
  - dask
  - dask-sql
  # - fastparquet
  - pyarrow
  - pip
  - sqlalchemy_schemadisplay
  - unidecode
  - xlsxwriter
  - pip:
    - dash-daq
    - dash-auth
    - dash-bootstrap-components
    - odfpy
    - uetl==0.0.9
