name: dash-dwbra

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.8
  - dash-core-components
  - dash-html-components
  - dash-renderer
  - dash-table
  - pip
  - sqlalchemy_schemadisplay
  - xlsxwriter
  - pip:
    - dash-daq
    - dash-auth
    - dash-bootstrap-components
    - odfpy
    - uetl==0.0.6
