name: Deploy to dev VM

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to dev VM using ssh-action
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEV_HOST }}
        username: ${{ secrets.DEV_HOST_USERNAME }}
        key: ${{ secrets.DEV_HOST_KEY}}
        port: ${{ secrets.DEV_HOST_PORT }}
        command_timeout: 120m
        shell: bash -l {0}
        script: |
          GIT_REPO=git@github.com:andrespp/dash-bra.git
          GIT_BRANCH=dev
          APP_PATH=~/dash-br
          DWBR_PATH=../dw-br
          CONDA_ENV=dash-dwbra

          echo `date` >> /tmp/lastrun

          # Check if repo does not exist, clone it
          if [ ! -d $APP_PATH ] ; then
            # Clone repo
            ssh-keyscan github.com >> ~/.ssh/known_hosts
            GIT_SSH_COMMAND="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
            git clone $GIT_REPO $APP_PATH
            cd $APP_PATH
            git checkout $GIT_BRANCH
          fi

          # Stop service
          cd $APP_PATH
          docker compose down

          # Update GIT repo
          git pull origin $GIT_BRANCH

          # Build docker image
          make setup

          # Retrieve data
          cp -alv $DWBR_PATH/data/parquet $APP_PATH/data/

          # Run app
          docker compose up -d
